### ISSUE TITLE
Healthcheck support

### ISSUE THREAD

**Issue by brunocascio** [Tecnativa/docker-socket-proxy#50] opened 2021-04-23 20:04 UTC
Hey guys,

Do you plan to add [healthchecks](https://docs.docker.com/engine/reference/builder/#healthcheck) to this image?

Thanks!

**Comment by joao-p-marques** [comment] 2021-04-26 06:31
Hi!

There was a PR implementing this feature, but due to the reasons explained [here](https://github.com/Tecnativa/docker-socket-proxy/pull/43#issuecomment-777298218) it hasn't been merged. 

I think, as @Yajo said there, that there is no real need to do that in the image level, and can be added on a container level by the user, avoiding all the performance issues mentioned there.

**Comment by Yajo** [comment] 2021-04-26 06:44
Duplicate of #43.

**Closed by Yajo** 2021-04-26 06:44 UTC
